### ISSUE TITLE
Automatically propagate "common" deployer properties as defaults

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#197]

**Comment by ericbottard** [comment]
Could you clarify what this is?

**Comment by cppwfs** [comment]
This is the discussion we started on the Task Launcher Cloud Foundry PR.  Basically this will allow deployer properties to be propagated to specific stream apps.  

The premise is that we would have a configurable list of apps in  SCDF that will receive these deployer properties when they are deployed.

**Comment by mminella** [comment]
@ericbottard This story is to provide default values from the SCDF server to any application that exposes deployer properties as app properties.  For example, when launching a partitioned batch job, if the job exposes the properties to configure a CF `TaskLauncher` and it's launched via the CF SCDF Server, the SCDF server should be able to introspect the properties for the job and inject the deployer ones it is using as defaults to the job module instead of requiring the user to define all those properties for every module that uses them.

**Comment by markpollack** [comment]
This is going to also be needed in other server impls.

**Comment by sabbyanandan** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-dataflow/issues/974.
