### ISSUE TITLE
How to register Data Flow with Eureka?

### ISSUE THREAD

**Issue by astetsa** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#272]
How to register Spring Cloud Data Flow for CF with eureka?

**Comment by markpollack** [comment]
You will need to checkout the tagged version of the server from github and add the dependency `spring-cloud-services-starter-service-registry` to the `spring-cloud-dataflow-server-cloudfoundry-autoconfig`  pom.xml file.  We don't include it by default I believe since a fatal error is thrown if the application can't find the discovery service and we don't want to make it a requirement for deploying SCDF.

The docs (when using the spring cloud services tile are here - 
http://docs.pivotal.io/spring-cloud-services/1-3/common/client-dependencies.html#service-registry

If you want to use Eureka outside the spring cloud services tile, then you will need to modify the pom.xml as you would for any app that uses OSS eureka.
