### ISSUE TITLE
REST API guide include can't reference snippets

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#348]
The generated REST Docs snippets are only available when building the core server docs.
In the CF specific docs (and also any other server flavor), those snippets are not available, rendering that section of the docs useless.

cc @trisberg @jvalkeal

**Comment by sabbyanandan** [comment]
Based on the discussion, as a suggestion, we will include the "link" to SCDF's [REST-APIs section](http://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#api-guide) (Similar to [Applications](http://docs.spring.io/spring-cloud-dataflow/docs/1.3.0.BUILD-SNAPSHOT/reference/htmlsingle/#applications)). Otherwise, we will have to _duplicate_ [all the includes](https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/master/spring-cloud-dataflow-docs/src/main/asciidoc/api-guide.adoc#) that gets generated at the release time.
