### ISSUE TITLE
Revisit LRU caching support in the context of Disk Quota 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#422]
As a developer, I'd like to review the configuration overrides for Disk Quota for the LRU caching, so we can determine the right approach towards the deciding factor for entry evictions. Currently, there appears to be confusion in regards to Disk Quota being defined in `%` vs. `size`, and they both operate differently. 

Depending on what gets set, there might be issues with the server failing to start.

**Comment by markpollack** [comment]
Removing the use of the LRUResourceLoader as it turns out we were only using for metadata artifacts since version 1.3.  Documentation has been updated to indicate that Boot's disk space health indicator in order to have PCF restart the data flow server if disk usage is low.  Will revisit how to have SCDF-PCF use Volume Services so more than 10G can be used.
