### ISSUE TITLE
Redis error in CF

### ISSUE THREAD

**Issue by linusviking** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#97]
I followed the http-cassandra sample and deployed a dataflow-server on Cloud Foundry. Created two services, Redis and Rabbit from CF Marketplace and bound to the app. I am able to connect the shell to the server endpoint. However, when registering the http module

> module register --type source --name http --uri maven://org.springframework.cloud.stream.app:http-source-rabbit:1.0.0.BUILD-SNAPSHOT --force

I get the following error "Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool". I have bound to Redis service version 2.8.23 

Is this an incompatibility issue and if yes, how can I make the cloud foundry dataflow server work with this particular version?

**Comment by sabbyanandan** [comment]
Hi, @linusviking:

Thanks for reporting this.

I believe [1.5.x release](http://docs.pivotal.io/redis/) of the PCF Redis-tile builds upon 3.0.x OSS Redis release. Which version of the Redis-tile are you using? 

There isn't any strong correlation for SCDF and Redis. Since this error relates to unsuccessful connection attempt with your Redis instance, can you bind and use this instance for any other app? Are you able to connect to this instance from `redis-cli`?

**Comment by linusviking** [comment]
Thanks @sabbyanandan 

The managed Redis service instance in my org is reporting version 2.8.23. I am able to bind to this service instance from a test app. Is there a way I change the jedis version in SCDF code?

**Comment by markpollack** [comment]
What version of jedis are you using?  SCDF is using jedis 2.7.3.  Is there a deeper stack trace you can post.  Generally speaking Jedis claims that 2.7.3 is fully compatible with redis server 2.8.x and 3.0.x.  See https://github.com/xetorthio/jedis

**Comment by markpollack** [comment]
I tested using the local spring cloud data flow server against redis-server 2.8.23 and the module register command worked.  There maybe something more subtle going on since in the case of cloud foundry it is the buildpack that is creating the connection factory whereas in the local data flow server it is done using spring boot autoconfiguration.


Here is one thing to try

and then add the following to the environment before launching the Data Flow Server on CF.

`$ cf set-env my-dataflow-server JBP_CONFIG_SPRING_AUTO_RECONFIGURATION '{enabled: false}'`

Also look at your test app to discover the actual HOST/PORT of the redis server host/port which will be in the `VCAP_SERVICES` environment variable.  

Then set additional env-vars for `spring.redis.host` and `spring.redis.port` so that boot will create the connection factory.   Not sure if a password env-var is needed. 

refresh the app and restart in CF.

**Comment by linusviking** [comment]
Thanks @markpollack - I am able to see the redis host/port my test app is bound to. Could you please say what'd be the cf set-env syntax for `spring.redis.host `and `spring.redis.port`?

**Comment by sabbyanandan** [comment]
@linusviking: The error message is so generic it could be that the server cannot connect to it, maybe the connection pool limit is reached, or there's indeed some incompatibility issue. Could you tail the server logs, redo the `register` command and share the entire stacktrace, please?

**Comment by linusviking** [comment]
@sabbyanandan @markpollack The issue has been resolved. It was a redis service broker issue in my org's CF instance. Thanks for your guidance.
